project_id = "ejrbfyvlkibbaufcyxtc"

[functions.send-password-reset]
verify_jwt = false

[functions.seed-quickstart]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.create-course-checkout]
verify_jwt = false

[functions.verify-course-purchase]
verify_jwt = false

[functions.stripe-connect-onboarding]
verify_jwt = false
