project_id = "twaljzxgbbkhhjjocilf"

[functions.send-survey-sms]
verify_jwt = false

[functions.send-survey-email]
verify_jwt = false

[functions.send-maintenance-request]
verify_jwt = false

[functions.bot-chat]
verify_jwt = false

[functions.builder-agent]
verify_jwt = false

[functions.code-agent]
verify_jwt = false

[functions.publish-site]
verify_jwt = false

[functions.contact-form]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.track-pageview]
verify_jwt = false

[functions.allowed-domains]
verify_jwt = false

[functions.serve-site]
verify_jwt = false
