import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

interface SyncRequest {
  projectId: string;
  projectName: string;
  siteSpec: Record<string, unknown>;
  reactCode?: string;
  repoName?: string;
  commitMessage?: string;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function getGitHubToken(supabaseClient: any, userId: string): Promise<string | null> {
  const { data, error } = await supabaseClient
    .from("github_connections")
    .select("access_token")
    .eq("user_id", userId)
    .single();

  if (error || !data) {
    console.error("Failed to get GitHub token:", error);
    return null;
  }

  return (data as { access_token: string }).access_token;
}

async function githubApi(token: string, endpoint: string, options: RequestInit = {}) {
  const response = await fetch(`https://api.github.com${endpoint}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github.v3+json",
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

  const data = await response.json();
  return { response, data };
}

function generateReactCode(projectName: string, siteSpec: Record<string, unknown>): string {
  const safeName = projectName.replace(/[^a-zA-Z0-9]/g, "");
  
  return `// Generated by Excellion Builder
// Project: ${projectName}
// Generated at: ${new Date().toISOString()}

import React from 'react';

// Site Specification
export const siteSpec = ${JSON.stringify(siteSpec, null, 2)};

// Main App Component
export default function ${safeName || "App"}() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* This is a generated React component from Excellion Builder */}
      {/* Site Name: ${(siteSpec as { name?: string }).name || projectName} */}
      <main>
        <h1 className="text-4xl font-bold text-center py-8">
          ${(siteSpec as { name?: string }).name || projectName}
        </h1>
        <p className="text-center text-muted-foreground">
          Edit this file to customize your site
        </p>
      </main>
    </div>
  );
}
`;
}

function generatePackageJson(projectName: string): string {
  return JSON.stringify({
    name: projectName.toLowerCase().replace(/[^a-z0-9]/g, "-"),
    version: "1.0.0",
    private: true,
    type: "module",
    scripts: {
      dev: "vite",
      build: "vite build",
      preview: "vite preview",
    },
    dependencies: {
      react: "^18.3.1",
      "react-dom": "^18.3.1",
    },
    devDependencies: {
      "@vitejs/plugin-react": "^4.3.1",
      vite: "^5.4.2",
      tailwindcss: "^3.4.1",
      autoprefixer: "^10.4.18",
      postcss: "^8.4.35",
    },
  }, null, 2);
}

function generateIndexHtml(projectName: string): string {
  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${projectName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>`;
}

function generateMainJsx(): string {
  return `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
`;
}

function generateIndexCss(): string {
  return `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --background: 0 0% 100%;
  --foreground: 222.2 84% 4.9%;
  --muted-foreground: 215.4 16.3% 46.9%;
}

.dark {
  --background: 222.2 84% 4.9%;
  --foreground: 210 40% 98%;
  --muted-foreground: 215 20.2% 65.1%;
}

body {
  background-color: hsl(var(--background));
  color: hsl(var(--foreground));
}
`;
}

function generateViteConfig(): string {
  return `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
});
`;
}

function generateTailwindConfig(): string {
  return `/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {},
  },
  plugins: [],
};
`;
}

function generatePostcssConfig(): string {
  return `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  const startTime = Date.now();

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      return new Response(JSON.stringify({ error: "Not authenticated" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const supabaseAdmin = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
    const supabaseUser = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
      global: { headers: { Authorization: authHeader } },
    });

    const { data: { user }, error: userError } = await supabaseUser.auth.getUser();
    if (userError || !user) {
      return new Response(JSON.stringify({ error: "Authentication failed" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const body: SyncRequest = await req.json();
    const { projectId, projectName, siteSpec, reactCode, repoName, commitMessage } = body;

    if (!projectId || !projectName || !siteSpec) {
      return new Response(JSON.stringify({ error: "Missing required fields" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Get GitHub token
    const token = await getGitHubToken(supabaseAdmin, user.id);
    if (!token) {
      return new Response(JSON.stringify({ error: "GitHub not connected", code: "NOT_CONNECTED" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Generate repo name if not provided
    const finalRepoName = repoName || `excellion-${projectName.toLowerCase().replace(/[^a-z0-9]/g, "-")}-${projectId.slice(0, 8)}`;
    const finalCommitMessage = commitMessage || `Update from Excellion Builder - ${new Date().toISOString()}`;

    console.log(`Syncing project ${projectId} to repo ${finalRepoName}`);

    // Get authenticated user's GitHub username
    const { data: ghUser } = await githubApi(token, "/user");
    const owner = ghUser.login;

    // Check if repo exists
    const { response: repoCheck, data: repoData } = await githubApi(token, `/repos/${owner}/${finalRepoName}`);
    
    let repoUrl: string;

    if (repoCheck.status === 404) {
      // Create new repo
      console.log("Creating new repository...");
      const { response: createResp, data: createData } = await githubApi(token, "/user/repos", {
        method: "POST",
        body: JSON.stringify({
          name: finalRepoName,
          description: `Generated by Excellion Builder - ${projectName}`,
          private: false,
          auto_init: true,
        }),
      });

      if (!createResp.ok) {
        console.error("Failed to create repo:", createData);
        return new Response(JSON.stringify({ error: "Failed to create repository", details: createData.message }), {
          status: 500,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }

      repoUrl = createData.html_url;
      console.log("Repository created:", repoUrl);

      // Wait a moment for repo to be ready
      await new Promise(resolve => setTimeout(resolve, 2000));
    } else if (repoCheck.ok) {
      repoUrl = repoData.html_url;
      console.log("Repository exists:", repoUrl);
    } else {
      return new Response(JSON.stringify({ error: "Failed to check repository" }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Prepare files to commit
    const appCode = reactCode || generateReactCode(projectName, siteSpec);
    
    const files = [
      { path: "src/App.jsx", content: appCode },
      { path: "src/main.jsx", content: generateMainJsx() },
      { path: "src/index.css", content: generateIndexCss() },
      { path: "index.html", content: generateIndexHtml(projectName) },
      { path: "package.json", content: generatePackageJson(projectName) },
      { path: "vite.config.js", content: generateViteConfig() },
      { path: "tailwind.config.js", content: generateTailwindConfig() },
      { path: "postcss.config.js", content: generatePostcssConfig() },
      { path: "excellion.json", content: JSON.stringify({ projectId, generatedAt: new Date().toISOString(), siteSpec }, null, 2) },
    ];

    // Get the default branch
    const { data: repoInfo } = await githubApi(token, `/repos/${owner}/${finalRepoName}`);
    const defaultBranch = repoInfo.default_branch || "main";

    // Get the latest commit SHA
    const { response: refResp, data: refData } = await githubApi(token, `/repos/${owner}/${finalRepoName}/git/refs/heads/${defaultBranch}`);
    
    let baseTreeSha: string;
    let parentSha: string;

    if (refResp.ok) {
      parentSha = refData.object.sha;
      const { data: commitData } = await githubApi(token, `/repos/${owner}/${finalRepoName}/git/commits/${parentSha}`);
      baseTreeSha = commitData.tree.sha;
    } else {
      // New repo, create initial commit
      const { data: treeData } = await githubApi(token, `/repos/${owner}/${finalRepoName}/git/trees`, {
        method: "POST",
        body: JSON.stringify({
          tree: files.map(f => ({
            path: f.path,
            mode: "100644",
            type: "blob",
            content: f.content,
          })),
        }),
      });

      const { data: commitData } = await githubApi(token, `/repos/${owner}/${finalRepoName}/git/commits`, {
        method: "POST",
        body: JSON.stringify({
          message: finalCommitMessage,
          tree: treeData.sha,
        }),
      });

      await githubApi(token, `/repos/${owner}/${finalRepoName}/git/refs`, {
        method: "POST",
        body: JSON.stringify({
          ref: `refs/heads/${defaultBranch}`,
          sha: commitData.sha,
        }),
      });

      // Update project with GitHub info
      await supabaseAdmin
        .from("builder_projects")
        .update({
          github_repo_url: repoUrl,
          github_last_synced_at: new Date().toISOString(),
        })
        .eq("id", projectId);

      const latency = Date.now() - startTime;
      console.log(`Sync completed in ${latency}ms`);

      return new Response(JSON.stringify({
        success: true,
        repoUrl,
        commitSha: commitData.sha,
        latencyMs: latency,
      }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Create new tree with files
    const { data: newTreeData } = await githubApi(token, `/repos/${owner}/${finalRepoName}/git/trees`, {
      method: "POST",
      body: JSON.stringify({
        base_tree: baseTreeSha,
        tree: files.map(f => ({
          path: f.path,
          mode: "100644",
          type: "blob",
          content: f.content,
        })),
      }),
    });

    // Create commit
    const { data: newCommitData } = await githubApi(token, `/repos/${owner}/${finalRepoName}/git/commits`, {
      method: "POST",
      body: JSON.stringify({
        message: finalCommitMessage,
        tree: newTreeData.sha,
        parents: [parentSha],
      }),
    });

    // Update ref
    await githubApi(token, `/repos/${owner}/${finalRepoName}/git/refs/heads/${defaultBranch}`, {
      method: "PATCH",
      body: JSON.stringify({
        sha: newCommitData.sha,
      }),
    });

    // Update project with GitHub info
    await supabaseAdmin
      .from("builder_projects")
      .update({
        github_repo_url: repoUrl,
        github_last_synced_at: new Date().toISOString(),
      })
      .eq("id", projectId);

    const latency = Date.now() - startTime;
    console.log(`Sync completed in ${latency}ms`);

    return new Response(JSON.stringify({
      success: true,
      repoUrl,
      commitSha: newCommitData.sha,
      latencyMs: latency,
    }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });

  } catch (error) {
    console.error("Sync to GitHub error:", error);
    const message = error instanceof Error ? error.message : "Unknown error";
    return new Response(JSON.stringify({ error: message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
