import { useState, useEffect, useRef } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Code, HelpCircle, Settings, Send, Loader2, Monitor, Tablet, Smartphone, LayoutGrid } from 'lucide-react';
import { SiteSpec } from '@/types/site-spec';
import { specFromChat } from '@/lib/specFromChat';
import { SiteRenderer } from './SiteRenderer';
import { supabase } from '@/integrations/supabase/client';
import { useSiteEditor } from '@/hooks/useSiteEditor';
import type { Json } from '@/integrations/supabase/types';

type GenerationStep = {
  id: number;
  label: string;
  status: 'pending' | 'active' | 'complete' | 'error';
};

type Message = {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  htmlCode?: string;
};

type PreviewMode = 'desktop' | 'tablet' | 'mobile';

type LocationState = {
  initialIdea?: string;
  projectId?: string;
};

const INITIAL_STEPS: GenerationStep[] = [
  { id: 1, label: 'Analyzing idea', status: 'pending' },
  { id: 2, label: 'Fetching URL info', status: 'pending' },
  { id: 3, label: 'Generating website', status: 'pending' },
  { id: 4, label: 'Building preview', status: 'pending' },
];

function extractHtmlFromResponse(text: string): { message: string; html: string | null } {
  const htmlMatch = text.match(/```html\s*([\s\S]*?)```/);
  if (htmlMatch) {
    const html = htmlMatch[1].trim();
    const message = text.replace(/```html[\s\S]*?```/, '').trim();
    return { message, html };
  }
  return { message: text, html: null };
}

function containsUrl(text: string): boolean {
  return /https?:\/\/[^\s<>"{}|\\^`[\]]+/i.test(text);
}

export function BuilderShell() {
  const location = useLocation();
  const navigate = useNavigate();
  const state = location.state as LocationState | null;
  const initialIdea = state?.initialIdea || '';
  const projectIdFromState = state?.projectId || null;

  const [idea, setIdea] = useState('');
  const [messages, setMessages] = useState<Message[]>([]);
  const [siteSpec, setSiteSpec] = useState<SiteSpec | null>(null);
  const [generatedHtml, setGeneratedHtml] = useState<string | null>(null);
  const [steps, setSteps] = useState<GenerationStep[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [previewMode, setPreviewMode] = useState<PreviewMode>('desktop');
  const [projectId, setProjectId] = useState<string | null>(projectIdFromState);
  const [projectName, setProjectName] = useState<string>('New Project');
  
  // Use the site editor hook for inline editing
  const editor = useSiteEditor(siteSpec, setSiteSpec);
  
  const hasAutoGeneratedRef = useRef(false);
  const hasLoadedProjectRef = useRef(false);

  useEffect(() => {
    if (projectId && !hasLoadedProjectRef.current) {
      hasLoadedProjectRef.current = true;
      loadProject(projectId);
    }
  }, [projectId]);

  const loadProject = async (id: string) => {
    const { data, error } = await supabase
      .from('builder_projects')
      .select('*')
      .eq('id', id)
      .single();

    if (error || !data) {
      console.error('Failed to load project:', error);
      toast.error('Failed to load project');
      return;
    }

    setProjectName(data.name);
    
    const spec = data.spec as { html?: string; messages?: Message[]; siteSpec?: SiteSpec } | null;
    if (spec) {
      if (spec.html) {
        setGeneratedHtml(spec.html);
      }
      if (spec.siteSpec) {
        setSiteSpec(spec.siteSpec);
      }
      if (spec.messages && Array.isArray(spec.messages)) {
        setMessages(spec.messages.map((m, i) => ({
          id: m.id || `loaded-${i}`,
          role: m.role,
          content: m.content,
          htmlCode: m.htmlCode,
        })));
      }
    }
  };

  useEffect(() => {
    if (initialIdea && !projectId && !siteSpec && !generatedHtml && !isGenerating && messages.length === 0 && !hasAutoGeneratedRef.current) {
      hasAutoGeneratedRef.current = true;
      setIdea(initialIdea);
      handleGenerate(initialIdea);
    }
  }, []);

  const updateStep = (stepId: number, status: GenerationStep['status']) => {
    setSteps((prev) =>
      prev.map((s) => (s.id === stepId ? { ...s, status } : s))
    );
  };

  const saveProject = async (html: string | null, allMessages: Message[], ideaText: string, currentSiteSpec: SiteSpec | null) => {
    const name = projectName !== 'New Project' ? projectName : ideaText.slice(0, 50);
    
    const projectData = {
      name,
      idea: ideaText,
      spec: { 
        html, 
        siteSpec: currentSiteSpec,
        messages: allMessages.map(m => ({
          id: m.id,
          role: m.role,
          content: m.content,
          htmlCode: m.htmlCode,
        }))
      } as unknown as Json,
    };

    if (projectId) {
      const { error } = await supabase
        .from('builder_projects')
        .update(projectData)
        .eq('id', projectId);

      if (error) {
        console.error('Failed to update project:', error);
      }
    } else {
      const { data, error } = await supabase
        .from('builder_projects')
        .insert(projectData)
        .select('id')
        .single();

      if (error) {
        console.error('Failed to save project:', error);
      } else if (data) {
        setProjectId(data.id);
        setProjectName(name);
        toast.success('Project saved!');
      }
    }
  };

  // Auto-save when siteSpec changes (from inline editing)
  useEffect(() => {
    if (siteSpec && projectId) {
      const firstUserMessage = messages.find(m => m.role === 'user');
      saveProject(generatedHtml, messages, firstUserMessage?.content || '', siteSpec);
    }
  }, [siteSpec]);

  const handleGenerate = async (inputIdea?: string) => {
    const ideaToUse = inputIdea || idea;
    if (!ideaToUse.trim()) return;

    const userMessage: Message = {
      id: Date.now().toString(),
      role: 'user',
      content: ideaToUse,
    };
    setMessages((prev) => [...prev, userMessage]);
    setIdea('');

    setIsGenerating(true);
    setGeneratedHtml(null);
    setSiteSpec(null);
    setSteps(INITIAL_STEPS.map((s) => ({ ...s, status: 'pending' })));

    const hasUrl = containsUrl(ideaToUse);

    try {
      updateStep(1, 'active');
      await new Promise((r) => setTimeout(r, 200));
      updateStep(1, 'complete');

      updateStep(2, 'active');
      if (hasUrl) {
        await new Promise((r) => setTimeout(r, 100));
      }
      updateStep(2, 'complete');

      updateStep(3, 'active');
      
      const chatMessages = [...messages, userMessage].map((m) => ({
        role: m.role,
        content: m.content,
      }));

      const response = await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/bot-chat`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY}`,
        },
        body: JSON.stringify({ messages: chatMessages }),
      });

      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.error || 'Failed to generate website');
      }

      const reader = response.body?.getReader();
      const decoder = new TextDecoder();
      let fullResponse = '';
      let textBuffer = '';

      if (reader) {
        while (true) {
          const { done, value } = await reader.read();
          if (done) break;
          
          textBuffer += decoder.decode(value, { stream: true });
          
          let newlineIndex: number;
          while ((newlineIndex = textBuffer.indexOf('\n')) !== -1) {
            let line = textBuffer.slice(0, newlineIndex);
            textBuffer = textBuffer.slice(newlineIndex + 1);
            
            if (line.endsWith('\r')) line = line.slice(0, -1);
            if (line.startsWith(':') || line.trim() === '') continue;
            if (!line.startsWith('data: ')) continue;
            
            const jsonStr = line.slice(6).trim();
            if (jsonStr === '[DONE]') break;
            
            try {
              const parsed = JSON.parse(jsonStr);
              const content = parsed.choices?.[0]?.delta?.content;
              if (content) fullResponse += content;
            } catch {
              // Partial JSON, continue
            }
          }
        }
      }

      updateStep(3, 'complete');

      updateStep(4, 'active');
      
      const { message: assistantText, html } = extractHtmlFromResponse(fullResponse);
      
      let newSiteSpec: SiteSpec | null = null;
      if (html) {
        setGeneratedHtml(html);
      } else {
        newSiteSpec = specFromChat(ideaToUse);
        setSiteSpec(newSiteSpec);
      }
      
      updateStep(4, 'complete');

      const assistantMessage: Message = {
        id: (Date.now() + 1).toString(),
        role: 'assistant',
        content: assistantText || 'Website generated! Check the preview on the right.',
        htmlCode: html || undefined,
      };
      const allMessages = [...messages, userMessage, assistantMessage];
      setMessages(allMessages);

      const firstUserMessage = allMessages.find(m => m.role === 'user');
      await saveProject(html, allMessages, firstUserMessage?.content || ideaToUse, newSiteSpec);
    } catch (error) {
      console.error('Generation error:', error);
      toast.error(error instanceof Error ? error.message : 'Failed to generate. Please try again.');
      setSteps((prev) =>
        prev.map((s) => (s.status === 'active' ? { ...s, status: 'error' } : s))
      );
    } finally {
      setIsGenerating(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleGenerate();
    }
  };

  const getPreviewWidth = () => {
    switch (previewMode) {
      case 'tablet': return 'max-w-[768px]';
      case 'mobile': return 'max-w-[375px]';
      default: return 'w-full';
    }
  };

  return (
    <div className="h-screen flex overflow-hidden bg-background">
      {/* Left Column - Chat */}
      <div className="w-[400px] border-r border-border flex flex-col bg-card/30">
        <ScrollArea className="flex-1 p-4">
          <div className="space-y-4">
            {messages.length === 0 && (
              <div className="text-center py-12">
                <p className="text-muted-foreground text-sm">
                  Describe your business idea to get started
                </p>
              </div>
            )}
            {messages.map((msg) => (
              <div
                key={msg.id}
                className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}
              >
                <div
                  className={`max-w-[85%] rounded-xl px-4 py-2 text-sm ${
                    msg.role === 'user'
                      ? 'bg-primary text-primary-foreground'
                      : 'bg-muted text-foreground'
                  }`}
                >
                  {msg.content}
                </div>
              </div>
            ))}
            {isGenerating && (
              <div className="flex justify-start">
                <div className="bg-muted rounded-xl px-4 py-2 text-sm text-muted-foreground flex items-center gap-2">
                  <Loader2 className="h-4 w-4 animate-spin" />
                  Generating...
                </div>
              </div>
            )}
          </div>
        </ScrollArea>

        <div className="border-t border-border p-4">
          <div className="flex items-center gap-2 bg-background border border-border rounded-xl px-4 py-2">
            <Input
              value={idea}
              onChange={(e) => setIdea(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder="Describe your app idea..."
              className="flex-1 border-0 bg-transparent focus-visible:ring-0 focus-visible:ring-offset-0 text-sm"
              disabled={isGenerating}
            />
            <Button
              size="icon"
              onClick={() => handleGenerate()}
              disabled={!idea.trim() || isGenerating}
              className="h-8 w-8 rounded-full bg-primary hover:bg-primary/90"
            >
              {isGenerating ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <Send className="h-4 w-4" />
              )}
            </Button>
          </div>
        </div>
      </div>

      {/* Right Column - Preview + Tabs */}
      <div className="flex-1 flex flex-col">
        <div className="h-12 border-b border-border flex items-center justify-between px-4 bg-card/30">
          <span className="text-sm text-muted-foreground truncate max-w-[200px]">
            {projectName}
          </span>

          <div className="flex items-center gap-1 bg-muted/50 rounded-lg p-1">
            <Button
              variant="ghost"
              size="icon"
              className={`h-7 w-7 ${previewMode === 'desktop' ? 'bg-background shadow-sm' : ''}`}
              onClick={() => setPreviewMode('desktop')}
            >
              <Monitor className="h-4 w-4" />
            </Button>
            <Button
              variant="ghost"
              size="icon"
              className={`h-7 w-7 ${previewMode === 'tablet' ? 'bg-background shadow-sm' : ''}`}
              onClick={() => setPreviewMode('tablet')}
            >
              <Tablet className="h-4 w-4" />
            </Button>
            <Button
              variant="ghost"
              size="icon"
              className={`h-7 w-7 ${previewMode === 'mobile' ? 'bg-background shadow-sm' : ''}`}
              onClick={() => setPreviewMode('mobile')}
            >
              <Smartphone className="h-4 w-4" />
            </Button>
          </div>

          <div className="flex items-center gap-4">
            <Tabs defaultValue="code" className="h-full">
              <TabsList className="bg-transparent h-full gap-2">
                <TabsTrigger value="code" className="text-xs gap-1.5 data-[state=active]:bg-muted">
                  <Code className="h-3.5 w-3.5" />
                  Code
                </TabsTrigger>
                <TabsTrigger value="questions" className="text-xs gap-1.5 data-[state=active]:bg-muted">
                  <HelpCircle className="h-3.5 w-3.5" />
                  Questions
                </TabsTrigger>
                <TabsTrigger value="debug" className="text-xs gap-1.5 data-[state=active]:bg-muted">
                  <Settings className="h-3.5 w-3.5" />
                  Debug
                </TabsTrigger>
              </TabsList>
            </Tabs>
            
            <Button
              variant="outline"
              size="sm"
              onClick={() => navigate('/secret-builder-hub')}
              className="gap-1.5 text-xs"
            >
              <LayoutGrid className="h-3.5 w-3.5" />
              My Hub
            </Button>
          </div>
        </div>

        <div className="flex-1 bg-muted/30 p-4 overflow-hidden">
          <div className={`h-full mx-auto ${getPreviewWidth()} transition-all duration-300`}>
            <div className="h-full bg-background rounded-xl shadow-lg overflow-hidden border border-border">
              {generatedHtml ? (
                <iframe
                  srcDoc={generatedHtml}
                  className="w-full h-full border-0"
                  title="Generated Website Preview"
                  sandbox="allow-scripts"
                />
              ) : siteSpec ? (
                <SiteRenderer 
                  siteSpec={siteSpec} 
                  isLoading={isGenerating}
                  onUpdateHeroContent={editor.updateHeroContent}
                  onUpdateFeaturesContent={editor.updateFeaturesContent}
                  onUpdateFeatureItem={editor.updateFeatureItem}
                  onUpdateSiteName={editor.updateSiteName}
                  onUpdateNavItem={editor.updateNavItem}
                  onReorderSections={editor.reorderSections}
                />
              ) : (
                <div className="h-full flex items-center justify-center">
                  <div className="text-center p-8">
                    <Monitor className="h-12 w-12 mx-auto mb-4 text-muted-foreground/50" />
                    <p className="text-muted-foreground">
                      No site generated yet. Enter an idea to see a live preview.
                    </p>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
